.TH MCEDIT-DEBIAN 1
.SH NAME
mcedit-debian \- mcedit wrapper
.br
.SH DESCRIPTION
This script is just a wrapper for 
.B mcedit,
(the Midnight Commander internal editor) to use with Debian
alternatives system.
.SH OPTIONS
Full list of supported options could be found on the 
.BR mcedit (1)
manpage.
.SH SEE ALSO
.BR mcedit (1),
.BR mc (1)
.SH AUTHOR
This manual page was written by Adam Byrtek <alpha@debian.org>, for
the Debian GNU/Linux system. 
