#! /bin/sh

set -e

case "$1" in
    configure|abort-upgrade)
	update-alternatives --install /usr/bin/view view /usr/bin/mcview 25
	update-alternatives --install /usr/bin/editor editor /usr/bin/mcedit 25
	[ ! -x /usr/bin/gtk-update-icon-cache ] || \
		/usr/bin/gtk-update-icon-cache -f /usr/share/icons/hicolor
	[ ! -x /usr/bin/maemo-select-menu-location ] || \
		/usr/bin/maemo-select-menu-location mc.desktop tana_fi_utilities
	;;
esac

#DEBHELPER#
